### ISSUE TITLE
Stats validation test for individual Changesets.

### ISSUE THREAD

**Issue by emi420** [hotosm/underpass#192]
Test for calculating stats from a Changeset file and compare them with results stored in a YAML file.

![Screen Shot 2022-05-09 at 14.11.42.png](https://images.zenhubusercontent.com/6230ac8e94a5cb2f9cc49ce2/707d5e5a-966b-4bdf-8b4f-e15a37374b8a)

**Comment by emi420** [comment]
For testing cases like the issue #73 , now you can download the Changeset file, create a config YAML and run the test:

`./testsuite/libunderpass.all/stats-test -f stats/107235440.xml -f stats/107235440.yaml`

The YAML file have the Changeset ID and a list of expected results:

```
config:
  - change_id:
      - 107235440
  - modified_highway:
      - 8
  - added_highway:
      - 8
```

This will be useful for testing and fixing individual cases, detected manually or using the feature for comparing stats with Insights, described in PR #189
