### ISSUE TITLE
Stats: waterway

### ISSUE THREAD

**Issue by emi420** [hotosm/underpass#256]
waterway = river, canal, stream, brook, drain, ditch

```yaml
waterway:
  way:
    - river
    - canal
    - stream
    - brook
    - drain
    - ditch
```
