### ISSUE TITLE
Stats: amenity

### ISSUE THREAD

**Issue by emi420** [hotosm/underpass#257]
amenity = *

```yaml
amenity:
  node:
    - amenity:
      - *
  way:
    - amenity:
      - *
```
